version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - 10001:10001
    environment:
      DB_HOST: host.docker.internal
    depends_on:
      - db
